language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  

# This triggers builds to run on the new TravisCI infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Install Composer package before testing
install:
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml